name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

concurrency:
  group: github.ref
  cancel-in-progress: true
jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [18,20]
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS Version ${{matrix.version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.version}}
    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ matrix.os }}-node-modules-${{hashFiles('package-lock.json')}}
    - name: Install Dependencies
      run: npm install

    - name: Unit Testing
      run: npm test
      
    - name: Archive Test Result
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.os}}-${{matrix.version}}-Mocha-Test-Result
        path: test-results.xml
  
  coverage:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [20]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS Version ${{matrix.version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.version}}
    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ matrix.os }}-node-modules-${{hashFiles('package-lock.json')}}
    - name: Install Dependencies
      run: npm install

    - name: Coverage
      run: npm run coverage